import type { MetadataRoute } from "next";

/**
 * Generated by Next rather than kept as a static file, so the icon paths stay
 * in step with the icons the app actually serves. The previous static manifest
 * pointed at PNGs that were never produced, which browsers reported as install
 * failures.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "OBOLO — Warehouse stock and valuation",
    short_name: "OBOLO",
    description: "Know what is in the warehouse and what it is worth.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#e4e6e1",
    theme_color: "#14171a",
    icons: [
      {
        src: "/icon.svg",
        sizes: "any",
        type: "image/svg+xml",
        purpose: "any",
      },
    ],
  };
}
