import type { MetadataRoute } from "next";

/**
 * Generated by Next rather than kept as a static file, so the icon paths stay
 * in step with the icons the app actually serves. The previous static manifest
 * pointed at PNGs that were never produced, which browsers reported as install
 * failures.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "OBOLO — Warehouse stock and valuation",
    short_name: "OBOLO",
    description: "Know what is in the warehouse and what it is worth.",
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait",
    background_color: "#e4e6e1",
    theme_color: "#14171a",
    icons: [
      // The vector first, so anything that can scale it does.
      { src: "/icon.svg", sizes: "any", type: "image/svg+xml", purpose: "any" },
      { src: "/icon-192.png", sizes: "192x192", type: "image/png", purpose: "any" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png", purpose: "any" },
      // Maskable is a different drawing, not the same one re-tagged: Android
      // crops to a circle inscribed in the middle 80%, so the glyph is set much
      // smaller inside a full-bleed square rather than a disc that gets shaved.
      {
        src: "/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
